# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "jekyll", ENV["JEKYLL_VERSION"] if ENV["JEKYLL_VERSION"]
gem "kramdown-parser-gfm" 
gem 'jekyll-font-awesome-sass'
gem "jekyll-feed", "~> 0.9"
gem "jekyll-seo-tag", "~> 2.1"